
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOffloat;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ILookupService", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas.research._2009._10.webngram.fault.ObjectFactory.class,
    com.microsoft.schemas.research._2009._10.webngram.frontend.ObjectFactory.class
})
public interface ILookupService {


    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetModels", action = "http://schemas.microsoft.com/research/2009/10/webngram/frontend/ILookupService/GetModels")
    @WebResult(name = "GetModelsResult", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
    @RequestWrapper(localName = "GetModels", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend", className = "com.microsoft.schemas.research._2009._10.webngram.frontend.GetModels")
    @ResponseWrapper(localName = "GetModelsResponse", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend", className = "com.microsoft.schemas.research._2009._10.webngram.frontend.GetModelsResponse")
    public ArrayOfstring getModels();

    /**
     * 
     * @param modelUrn
     * @param phrase
     * @param authorizationToken
     * @return
     *     returns java.lang.Float
     * @throws ILookupServiceGetProbabilityServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetProbability", action = "http://schemas.microsoft.com/research/2009/10/webngram/frontend/ILookupService/GetProbability")
    @WebResult(name = "GetProbabilityResult", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
    @RequestWrapper(localName = "GetProbability", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend", className = "com.microsoft.schemas.research._2009._10.webngram.frontend.GetProbability")
    @ResponseWrapper(localName = "GetProbabilityResponse", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend", className = "com.microsoft.schemas.research._2009._10.webngram.frontend.GetProbabilityResponse")
    public Float getProbability(
        @WebParam(name = "authorizationToken", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
        String authorizationToken,
        @WebParam(name = "modelUrn", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
        String modelUrn,
        @WebParam(name = "phrase", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
        String phrase)
        throws ILookupServiceGetProbabilityServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param modelUrn
     * @param phrases
     * @param authorizationToken
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOffloat
     * @throws ILookupServiceGetProbabilitiesServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetProbabilities", action = "http://schemas.microsoft.com/research/2009/10/webngram/frontend/ILookupService/GetProbabilities")
    @WebResult(name = "GetProbabilitiesResult", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
    @RequestWrapper(localName = "GetProbabilities", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend", className = "com.microsoft.schemas.research._2009._10.webngram.frontend.GetProbabilities")
    @ResponseWrapper(localName = "GetProbabilitiesResponse", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend", className = "com.microsoft.schemas.research._2009._10.webngram.frontend.GetProbabilitiesResponse")
    public ArrayOffloat getProbabilities(
        @WebParam(name = "authorizationToken", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
        String authorizationToken,
        @WebParam(name = "modelUrn", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
        String modelUrn,
        @WebParam(name = "phrases", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
        ArrayOfstring phrases)
        throws ILookupServiceGetProbabilitiesServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param modelUrn
     * @param phrase
     * @param authorizationToken
     * @return
     *     returns java.lang.Float
     * @throws ILookupServiceGetConditionalProbabilityServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetConditionalProbability", action = "http://schemas.microsoft.com/research/2009/10/webngram/frontend/ILookupService/GetConditionalProbability")
    @WebResult(name = "GetConditionalProbabilityResult", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
    @RequestWrapper(localName = "GetConditionalProbability", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend", className = "com.microsoft.schemas.research._2009._10.webngram.frontend.GetConditionalProbability")
    @ResponseWrapper(localName = "GetConditionalProbabilityResponse", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend", className = "com.microsoft.schemas.research._2009._10.webngram.frontend.GetConditionalProbabilityResponse")
    public Float getConditionalProbability(
        @WebParam(name = "authorizationToken", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
        String authorizationToken,
        @WebParam(name = "modelUrn", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
        String modelUrn,
        @WebParam(name = "phrase", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
        String phrase)
        throws ILookupServiceGetConditionalProbabilityServiceFaultFaultFaultMessage
    ;

    /**
     * 
     * @param modelUrn
     * @param phrases
     * @param authorizationToken
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOffloat
     * @throws ILookupServiceGetConditionalProbabilitiesServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetConditionalProbabilities", action = "http://schemas.microsoft.com/research/2009/10/webngram/frontend/ILookupService/GetConditionalProbabilities")
    @WebResult(name = "GetConditionalProbabilitiesResult", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
    @RequestWrapper(localName = "GetConditionalProbabilities", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend", className = "com.microsoft.schemas.research._2009._10.webngram.frontend.GetConditionalProbabilities")
    @ResponseWrapper(localName = "GetConditionalProbabilitiesResponse", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend", className = "com.microsoft.schemas.research._2009._10.webngram.frontend.GetConditionalProbabilitiesResponse")
    public ArrayOffloat getConditionalProbabilities(
        @WebParam(name = "authorizationToken", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
        String authorizationToken,
        @WebParam(name = "modelUrn", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
        String modelUrn,
        @WebParam(name = "phrases", targetNamespace = "http://schemas.microsoft.com/research/2009/10/webngram/frontend")
        ArrayOfstring phrases)
        throws ILookupServiceGetConditionalProbabilitiesServiceFaultFaultFaultMessage
    ;

}
